Repository Domitory-CheckMate/BackEnd, pull requests merged in 2024-01, with the labels that each got.

#11 [feat] 로그인 및 회원가입 기능
  src/main/java/org/gachon/checkmate/domain/member/controller/MemberController.java
  src/main/java/org/gachon/checkmate/domain/member/dto/request/MemberSignInRequestDto.java
  src/main/java/org/gachon/checkmate/domain/member/dto/request/MemberSignUpRequestDto.java
  src/main/java/org/gachon/checkmate/domain/member/dto/request/PasswordResetRequestDto.java
  src/main/java/org/gachon/checkmate/domain/member/dto/response/MemberSignInResponseDto.java
  src/main/java/org/gachon/checkmate/domain/member/dto/response/MemberSignUpResponseDto.java
  src/main/java/org/gachon/checkmate/domain/member/entity/ProfileImageType.java
  src/main/java/org/gachon/checkmate/domain/member/entity/User.java
  src/main/java/org/gachon/checkmate/domain/member/repository/UserRepository.java
  src/main/java/org/gachon/checkmate/domain/member/service/MemberService.java
  src/main/java/org/gachon/checkmate/domain/post/converter/RoomTypeConverter.java
  src/main/java/org/gachon/checkmate/domain/post/entity/Post.java
  src/main/java/org/gachon/checkmate/domain/post/entity/RoomType.java
  src/main/java/org/gachon/checkmate/global/config/auth/SecurityConfig.java
  src/main/java/org/gachon/checkmate/global/error/ErrorCode.java
Labels: FEAT

#14 [feat] 키워드 게시물 조회 api 구현
  src/main/java/org/gachon/checkmate/domain/post/controller/PostController.java
  src/main/java/org/gachon/checkmate/domain/post/dto/response/PostSearchElementResponseDto.java
  src/main/java/org/gachon/checkmate/domain/post/dto/response/PostSearchResponseDto.java
  src/main/java/org/gachon/checkmate/domain/post/repository/PostQuerydslRepository.java
  src/main/java/org/gachon/checkmate/domain/post/service/PostService.java
Labels: FEAT

#16 [fix] keyword 중심 search 정렬 기준 반영
  src/main/java/org/gachon/checkmate/domain/post/controller/PostController.java
  src/main/java/org/gachon/checkmate/domain/post/entity/SortType.java
  src/main/java/org/gachon/checkmate/domain/post/repository/PostQuerydslRepository.java
  src/main/java/org/gachon/checkmate/domain/post/service/PostService.java
  src/main/java/org/gachon/checkmate/global/error/ErrorCode.java
  src/main/java/org/gachon/checkmate/global/utils/PagingUtils.java
Labels: FEAT, FIX

#18 [feat] 게시물 전체 조회 api 구현
  src/main/java/org/gachon/checkmate/domain/post/controller/PostController.java
  src/main/java/org/gachon/checkmate/domain/post/repository/PostQuerydslRepository.java
  src/main/java/org/gachon/checkmate/domain/post/service/PostService.java
Labels: FEAT

#19 [feat] 체크리스트 관련 기능
  src/main/java/org/gachon/checkmate/domain/checkList/controller/CheckListController.java
  src/main/java/org/gachon/checkmate/domain/checkList/dto/request/CheckListRequestDto.java
  src/main/java/org/gachon/checkmate/domain/checkList/dto/response/CheckListResponseDto.java
  src/main/java/org/gachon/checkmate/domain/checkList/entity/CheckList.java
  src/main/java/org/gachon/checkmate/domain/checkList/repository/CheckListRepository.java
  src/main/java/org/gachon/checkmate/domain/checkList/service/CheckListService.java
  src/main/java/org/gachon/checkmate/domain/member/entity/User.java
  src/main/java/org/gachon/checkmate/global/config/WebConfig.java
  src/main/java/org/gachon/checkmate/global/error/ErrorCode.java
Labels: FEAT

#23 [feat] 마이페이지 조회 및 로그인 로직 추가
  build.gradle
  src/main/java/org/gachon/checkmate/domain/member/controller/MemberController.java
  src/main/java/org/gachon/checkmate/domain/member/dto/request/MemberReissueTokenRequestDto.java
  src/main/java/org/gachon/checkmate/domain/member/dto/request/ProfileImgRequestDto.java
  src/main/java/org/gachon/checkmate/domain/member/dto/response/MemberReissueTokenResponseDto.java
  src/main/java/org/gachon/checkmate/domain/member/dto/response/MypageResponseDto.java
  src/main/java/org/gachon/checkmate/domain/member/entity/ProfileImageType.java
  src/main/java/org/gachon/checkmate/domain/member/entity/RefreshToken.java
  src/main/java/org/gachon/checkmate/domain/member/entity/User.java
  src/main/java/org/gachon/checkmate/domain/member/repository/RefreshTokenRepository.java
  src/main/java/org/gachon/checkmate/domain/member/service/MemberService.java
  src/main/java/org/gachon/checkmate/global/config/RedisConfig.java
  src/main/java/org/gachon/checkmate/global/config/auth/SecurityConfig.java
  src/main/java/org/gachon/checkmate/global/config/auth/jwt/JwtProvider.java
  src/main/java/org/gachon/checkmate/global/error/ErrorCode.java
Labels: FEAT

#26 [feat] 게시글 작성 api 구현
  build.gradle
  src/main/java/org/gachon/checkmate/domain/checkList/entity/PostCheckList.java
  src/main/java/org/gachon/checkmate/domain/checkList/repository/PostCheckListRepository.java
  src/main/java/org/gachon/checkmate/domain/member/entity/User.java
  src/main/java/org/gachon/checkmate/domain/post/controller/PostController.java
  src/main/java/org/gachon/checkmate/domain/post/dto/request/PostCreateRequestDto.java
  src/main/java/org/gachon/checkmate/domain/post/entity/Post.java
  src/main/java/org/gachon/checkmate/domain/post/repository/PostQuerydslRepository.java
  src/main/java/org/gachon/checkmate/domain/post/repository/PostRepository.java
  src/main/java/org/gachon/checkmate/domain/post/service/PostService.java
  src/main/java/org/gachon/checkmate/global/error/ErrorCode.java
Labels: FEAT

#28 [fix] 성별 검색 필터 기능 추가
  src/main/java/org/gachon/checkmate/domain/member/entity/GenderType.java
  src/main/java/org/gachon/checkmate/domain/post/controller/PostController.java
  src/main/java/org/gachon/checkmate/domain/post/dto/response/PostSearchElementResponseDto.java
  src/main/java/org/gachon/checkmate/domain/post/dto/support/PostSearchCondition.java
  src/main/java/org/gachon/checkmate/domain/post/dto/support/PostSearchDto.java
  src/main/java/org/gachon/checkmate/domain/post/repository/PostQuerydslRepository.java
  src/main/java/org/gachon/checkmate/domain/post/service/PostService.java
  src/main/java/org/gachon/checkmate/global/config/auth/SecurityConfig.java
Labels: FEAT

#30 [refactor] 게시물 service 코드 정리
  src/main/java/org/gachon/checkmate/domain/post/controller/PostController.java
  src/main/java/org/gachon/checkmate/domain/post/repository/PostCustomRepository.java
  src/main/java/org/gachon/checkmate/domain/post/repository/PostCustomRepositoryImpl.java
  src/main/java/org/gachon/checkmate/domain/post/repository/PostRepository.java
  src/main/java/org/gachon/checkmate/domain/post/service/PostService.java
Labels: REFACTOR

#33 [feat] 게시물 생성 지난 시간 date 예외 처리
  src/main/java/org/gachon/checkmate/domain/post/repository/PostCustomRepositoryImpl.java
  src/main/java/org/gachon/checkmate/domain/post/service/PostService.java
  src/main/java/org/gachon/checkmate/global/error/ErrorCode.java
  src/main/java/org/gachon/checkmate/global/utils/PagingUtils.java
Labels: FEAT

#36 [feat] 스크랩, 내가 작성한 게시글 조회 api 구현
  src/main/java/org/gachon/checkmate/domain/member/converter/UserStateConverter.java
  src/main/java/org/gachon/checkmate/domain/member/entity/User.java
  src/main/java/org/gachon/checkmate/domain/member/entity/UserState.java
  src/main/java/org/gachon/checkmate/domain/post/controller/PostController.java
  src/main/java/org/gachon/checkmate/domain/post/converter/PostStateConverter.java
  src/main/java/org/gachon/checkmate/domain/post/dto/response/PostDetailResponseDto.java
  src/main/java/org/gachon/checkmate/domain/post/dto/response/PostSearchElementResponseDto.java
  src/main/java/org/gachon/checkmate/domain/post/dto/support/PostPagingSearchCondition.java
  src/main/java/org/gachon/checkmate/domain/post/dto/support/PostSearchDto.java
  src/main/java/org/gachon/checkmate/domain/post/entity/Post.java
  src/main/java/org/gachon/checkmate/domain/post/entity/PostState.java
  src/main/java/org/gachon/checkmate/domain/post/repository/PostCustomRepository.java
  src/main/java/org/gachon/checkmate/domain/post/repository/PostCustomRepositoryImpl.java
  src/main/java/org/gachon/checkmate/domain/post/service/PostService.java
  src/main/java/org/gachon/checkmate/domain/scrap/controller/ScrapController.java
  src/main/java/org/gachon/checkmate/domain/scrap/dto/request/ScrapRequestDto.java
  src/main/java/org/gachon/checkmate/domain/scrap/dto/support/ScrapSearchCondition.java
  src/main/java/org/gachon/checkmate/domain/scrap/entity/Scrap.java
  src/main/java/org/gachon/checkmate/domain/scrap/repository/ScrapCustomRepository.java
  src/main/java/org/gachon/checkmate/domain/scrap/repository/ScrapCustomRepositoryImpl.java
  src/main/java/org/gachon/checkmate/domain/scrap/repository/ScrapRepository.java
  src/main/java/org/gachon/checkmate/domain/scrap/service/ScrapService.java
Labels: FEAT

#38 [feat] 게시글 수정 및 상태 변경
  src/main/java/org/gachon/checkmate/domain/checkList/entity/PostCheckList.java
  src/main/java/org/gachon/checkmate/domain/post/controller/PostController.java
  src/main/java/org/gachon/checkmate/domain/post/dto/request/PostStateUpdateRequestDto.java
  src/main/java/org/gachon/checkmate/domain/post/dto/request/PostUpdateRequestDto.java
  src/main/java/org/gachon/checkmate/domain/post/dto/response/PostStateUpdateResponseDto.java
  src/main/java/org/gachon/checkmate/domain/post/dto/response/PostUpdateResponseDto.java
  src/main/java/org/gachon/checkmate/domain/post/entity/Post.java
  src/main/java/org/gachon/checkmate/domain/post/service/PostService.java
  src/main/java/org/gachon/checkmate/global/error/ErrorCode.java
Labels: FEAT

#41 [fix] 체크리스트 흡연 여부 항목 추가
  src/main/java/org/gachon/checkmate/domain/checkList/converter/LifePatterTypeConverter.java
  src/main/java/org/gachon/checkmate/domain/checkList/converter/LifePatternTypeConverter.java
  src/main/java/org/gachon/checkmate/domain/checkList/converter/SmokeTypeConverter.java
  src/main/java/org/gachon/checkmate/domain/checkList/dto/request/CheckListRequestDto.java
  src/main/java/org/gachon/checkmate/domain/checkList/dto/response/CheckListResponseDto.java
  src/main/java/org/gachon/checkmate/domain/checkList/entity/CheckList.java
  src/main/java/org/gachon/checkmate/domain/checkList/entity/LifePatternType.java
  src/main/java/org/gachon/checkmate/domain/checkList/entity/PostCheckList.java
  src/main/java/org/gachon/checkmate/domain/checkList/entity/SmokeType.java
  src/main/java/org/gachon/checkmate/domain/checkList/service/CheckListService.java
  src/main/java/org/gachon/checkmate/domain/member/entity/User.java
  src/main/java/org/gachon/checkmate/domain/post/service/PostService.java
  src/main/java/org/gachon/checkmate/domain/scrap/service/ScrapService.java
Labels: FIX

#44 [feat] 게시물, 채팅 신고
  src/main/java/org/gachon/checkmate/domain/report/controller/ReportController.java
  src/main/java/org/gachon/checkmate/domain/report/dto/request/ChatRoomReportRequestDto.java
  src/main/java/org/gachon/checkmate/domain/report/dto/request/PostReportRequestDto.java
  src/main/java/org/gachon/checkmate/domain/report/entity/ChatRoomReport.java
  src/main/java/org/gachon/checkmate/domain/report/entity/PostReport.java
  src/main/java/org/gachon/checkmate/domain/report/repository/ChatRoomReportRepository.java
  src/main/java/org/gachon/checkmate/domain/report/repository/PostReportRepository.java
  src/main/java/org/gachon/checkmate/domain/report/service/ReportService.java
  src/main/java/org/gachon/checkmate/global/error/ErrorCode.java
Labels: FEAT

#45 [feat] 회원탈퇴 기능
  src/main/java/org/gachon/checkmate/domain/chat/entity/ChatRoom.java
  src/main/java/org/gachon/checkmate/domain/chat/repository/ChatRoomCustomRepository.java
  src/main/java/org/gachon/checkmate/domain/chat/repository/ChatRoomCustomRepositoryImpl.java
  src/main/java/org/gachon/checkmate/domain/chat/repository/ChatRoomRepository.java
  src/main/java/org/gachon/checkmate/domain/chat/service/ChatService.java
  src/main/java/org/gachon/checkmate/domain/checkList/entity/CheckList.java
  src/main/java/org/gachon/checkmate/domain/member/controller/MemberController.java
  src/main/java/org/gachon/checkmate/domain/member/entity/User.java
  src/main/java/org/gachon/checkmate/domain/member/service/MemberService.java
  src/main/java/org/gachon/checkmate/domain/report/entity/ChatRoomReport.java
  src/main/java/org/gachon/checkmate/domain/report/service/ReportService.java
Labels: FEAT

#47 [feat] 비밀번호 변경 시에 사용할 이메일 인증 API
  src/main/java/org/gachon/checkmate/domain/member/controller/MemberController.java
  src/main/java/org/gachon/checkmate/domain/member/service/MemberService.java
  src/main/java/org/gachon/checkmate/global/config/auth/SecurityConfig.java
  src/main/java/org/gachon/checkmate/global/error/ErrorCode.java
Labels: FEAT

#52 [feat] 학과정보
  src/main/java/org/gachon/checkmate/domain/department/controller/DepartmentController.java
  src/main/java/org/gachon/checkmate/domain/department/dto/response/DepartmentNameResponseDto.java
  src/main/java/org/gachon/checkmate/domain/department/entity/Department.java
  src/main/java/org/gachon/checkmate/domain/department/repository/DepartmentCustomRepository.java
  src/main/java/org/gachon/checkmate/domain/department/repository/DepartmentCustomRepositoryImpl.java
  src/main/java/org/gachon/checkmate/domain/department/repository/DepartmentRepository.java
  src/main/java/org/gachon/checkmate/domain/department/service/DepartmentService.java
  src/main/java/org/gachon/checkmate/global/config/auth/SecurityConfig.java
Labels: FEAT

#54 [fix] 정렬기준 default 값 변경
  src/main/java/org/gachon/checkmate/domain/checkList/converter/CallTypeConverter.java
  src/main/java/org/gachon/checkmate/domain/checkList/converter/EarPhoneTypeConverter.java
  src/main/java/org/gachon/checkmate/domain/checkList/converter/NoiseTypeConverter.java
  src/main/java/org/gachon/checkmate/domain/checkList/dto/request/CheckListRequestDto.java
  src/main/java/org/gachon/checkmate/domain/checkList/dto/response/CheckListResponseDto.java
  src/main/java/org/gachon/checkmate/domain/checkList/entity/CallType.java
  src/main/java/org/gachon/checkmate/domain/checkList/entity/CheckList.java
  src/main/java/org/gachon/checkmate/domain/checkList/entity/CleanType.java
  src/main/java/org/gachon/checkmate/domain/checkList/entity/DrinkType.java
  src/main/java/org/gachon/checkmate/domain/checkList/entity/EarPhoneType.java
  src/main/java/org/gachon/checkmate/domain/checkList/entity/HomeType.java
  src/main/java/org/gachon/checkmate/domain/checkList/entity/PostCheckList.java
  src/main/java/org/gachon/checkmate/domain/checkList/utils/MatchRateCalculator.java
  src/main/java/org/gachon/checkmate/domain/post/utils/PostSortType.java
Labels: FIX

#56 [fix] api 연동 오류 해결
  src/main/java/org/gachon/checkmate/domain/member/dto/response/MemberSignInResponseDto.java
  src/main/java/org/gachon/checkmate/domain/member/service/MemberService.java
  src/main/java/org/gachon/checkmate/domain/post/controller/PostController.java
  src/main/java/org/gachon/checkmate/domain/post/converter/DormitoryTypeConverter.java
  src/main/java/org/gachon/checkmate/domain/post/dto/request/PostCreateRequestDto.java
  src/main/java/org/gachon/checkmate/domain/post/dto/request/PostUpdateRequestDto.java
  src/main/java/org/gachon/checkmate/domain/post/dto/response/PostDetailResponseDto.java
  src/main/java/org/gachon/checkmate/domain/post/dto/support/PostDetailDto.java
  src/main/java/org/gachon/checkmate/domain/post/dto/support/PostSearchCondition.java
  src/main/java/org/gachon/checkmate/domain/post/entity/DormitoryType.java
  src/main/java/org/gachon/checkmate/domain/post/entity/Post.java
  src/main/java/org/gachon/checkmate/domain/post/repository/PostCustomRepositoryImpl.java
  src/main/java/org/gachon/checkmate/domain/post/service/PostService.java
  src/main/java/org/gachon/checkmate/global/error/ErrorCode.java
  src/main/java/org/gachon/checkmate/global/utils/PagingUtils.java
Labels: FIX

#58 [fix] 이전 채팅내역 조회 response 수정 및 response 경로 변경
  src/main/java/org/gachon/checkmate/domain/chat/controller/ChatController.java
  src/main/java/org/gachon/checkmate/domain/chat/dto/response/ChatListResponseDto.java
  src/main/java/org/gachon/checkmate/domain/chat/service/ChatService.java
Labels: FIX

#62 [fix] 채팅 읽음 버그 수정
  src/main/java/org/gachon/checkmate/domain/chat/mongorepository/ChatCustomRepositoryImpl.java
Labels: FIX

#64 [fix] checklist api 오류 해결
  src/main/java/org/gachon/checkmate/domain/checkList/controller/CheckListController.java
  src/main/java/org/gachon/checkmate/domain/checkList/dto/request/CheckListRequestDto.java
  src/main/java/org/gachon/checkmate/domain/checkList/dto/support/CheckListEnumDto.java
  src/main/java/org/gachon/checkmate/domain/checkList/entity/CheckList.java
  src/main/java/org/gachon/checkmate/domain/checkList/entity/PostCheckList.java
  src/main/java/org/gachon/checkmate/domain/checkList/service/CheckListService.java
  src/main/java/org/gachon/checkmate/domain/post/controller/PostController.java
  src/main/java/org/gachon/checkmate/domain/post/dto/request/PostCreateRequestDto.java
  src/main/java/org/gachon/checkmate/domain/post/dto/request/PostRequestDto.java
  src/main/java/org/gachon/checkmate/domain/post/dto/request/PostUpdateRequestDto.java
  src/main/java/org/gachon/checkmate/domain/post/dto/support/PostEnumDto.java
  src/main/java/org/gachon/checkmate/domain/post/entity/Post.java
  src/main/java/org/gachon/checkmate/domain/post/service/PostService.java
Labels: FIX

#66 [feat] cors 배포주소 추가
  src/main/java/org/gachon/checkmate/global/config/CorsConfig.java
Labels: FEAT
